# Generated by Django 4.1.7 on 2023-04-08 19:38

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTable',
            fields=[
                ('userID', models.CharField(default=api.models.generate_unique_id, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('surname', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('company', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to=api.models.upload_to)),
                ('coverPage', models.ImageField(blank=True, null=True, upload_to=api.models.upload_to)),
                ('website', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('companyPhone', models.CharField(blank=True, max_length=64, null=True)),
                ('mail', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('addressCompany', models.CharField(blank=True, max_length=128, null=True)),
                ('location', models.JSONField(blank=True, default=dict, null=True)),
                ('vergiNo', models.CharField(blank=True, max_length=512, null=True)),
                ('iban', models.CharField(blank=True, max_length=512, null=True)),
                ('socialLinks', models.JSONField(blank=True, default={'discord': {'activated': 0, 'link': ''}, 'facebook': {'activated': 0, 'link': ''}, 'instagram': {'activated': 0, 'link': ''}, 'linkedin': {'activated': 0, 'link': ''}, 'messenger': {'activated': 0, 'link': ''}, 'pinterest': {'activated': 0, 'link': ''}, 'reddit': {'activated': 0, 'link': ''}, 'snapchat': {'activated': 0, 'link': ''}, 'spotify': {'activated': 0, 'link': ''}, 'telegram': {'activated': 0, 'link': ''}, 'tiktok': {'activated': 0, 'link': ''}, 'twitter': {'activated': 0, 'link': ''}, 'vsco': {'activated': 0, 'link': ''}}, null=True)),
                ('externalLinks', models.JSONField(blank=True, default=[], null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='extraUserFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificationCode', models.CharField(default=api.models.generate_random_code, max_length=64)),
                ('isVerified', models.BooleanField(blank=True, default=False, null=True)),
                ('resetCode', models.CharField(default=api.models.generate_random_code, max_length=64)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
